version: "3"
services:
  #mongodb:
  #  image: mongo:3.2.4
  #  container_name: "swapimongodb"
  #  ports:
  #    - 27017:27017
  #  volumes:
  #    - ./mongo-volume:/data/db
  api:
    image: pedrogonic/swapiimage
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: swapi
    ports:
      - 8090:8080
  #  links:
  #    - swapimongodb