version: "2.1"
services:
  swapimongodb:
    image: mongo:3.2.4
    volumes:
      - ./mongo-volume:/data/db
    restart: always
    container_name: "swapimongodb"
    ports:
      - 27017:27017

  api:
    container_name: swapi
    restart: always
    depends_on:
      - swapimongodb
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8090:8080