version: "2.1"
services:
  swapimongodb:
    image: mongo:3.2.4
    volumes:
      - ./mongo-volume:/data/db
    restart: always
    container_name: "swapimongodb"
    ports:
      - 27017:27017

  swapiredis:
    image: redis:6.0-rc-alpine
    restart: always
    container_name: "swapiredis"
    ports:
      - 6379:6379

  api:
    container_name: swapi
    restart: always
    depends_on:
      - swapimongodb
      - swapiredis
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8090:8080